### ISSUE TITLE
[Feature request] Gestion des familiers

### ISSUE THREAD

**Issue by whinette** [Crocmagnon/charasheet#48]
Plusieurs classes ont a disposition des familiers, avec une gestion des stats différentes des personnages.
Il serait très pratique de pouvoir les gérer depuis charasheet.

Le forgesort à accès à un golem. Le druide à un animal.
Leurs caractéristiques sont résumées par des bonus/malus aux jets.

Exemple ci dessous pour les Golems : 

Créature non vivante
Initiative : forgesort
Défense : 14
Attaque : niveau du forgesort + mod force
PV : 4x niveau du forgesort
Récupération PV : 1d6/rang + Mod Intelligence forgesort PV pour une heure de réparation
Dégats : 1d8 +1
* Force : +1
* Dextérité : -1
* Constitution : +10
* Intelligence : -4
* Sagesse : -3
* Charisme : -4

Dans le cas du golem, il acquière des compétences / gain en stat grâce à la voie "Golem" du forgesort : https://www.co-drs.org/fr/jeu/profils/forgesort

Exemple pour un familier druide : 

Créature vivante
Initiative : 18 (ou règle du dé)
Défense : 16
Attaque : niveau du forgesort + mod force
PV : 4x niveau du druide
Récupération PV : règles habituelles
Dégats : 1d6 +2
* Force : +2
* Dextérité : +4*
* Constitution : +2
* Intelligence : -3
* Sagesse : +2*
* Charisme : -2

\* ces carac utilisent la règle d'avantage (deux d20 sur les tests, le MJ retiens le meilleur jet)
Lorsque le druide acquière 4 dans la voie du fauce, les carac du familier sont buff : https://www.co-drs.org/fr/jeu/profils/druide

**Comment by Crocmagnon** [comment]
Modèle :
* modifiers caractéristiques (force, dex, etc) : int
* damage : charfield
* initiative : int
* def : int
* attaque : int
* pv max : int
* pv : int -> modifiables via l'interface
* récupération : text
* notes : text
* personnage : FK

interface :
* possibilité pour un joueur d'ajouter autant de familiers que nécessaire à son perso
* les familiers sont affichés sur la fiche de personnage, possible de modifier les PV comme pour les perso
* possible de modifier un familier via un formulaire, utile par ex lors d'une prise de niveau etc

**Comment by Crocmagnon** [comment]
Parcours utilisateur : 

Je suis sur la fiche de mon personnage. Lorsque je clique sur le bouton permettant d'ajouter un familier, un formulaire apparaît permettant de saisir les informations du familier. Quand j'enregistre, le formulaire disparaît et ma page de personnage est affichée et contient désormais mon familier.

Je peux rajouter autant de familiers que je le souhaite.

Je peux modifier mes familiers. Lorsque je clique sur le bouton pour modifier un familier existant, j'ai le même formulaire que précédemment pré-rempli avec les valeurs actuelles de mon familier.

Je peux supprimer mes familiers. Lorsque je supprime un familier, j'atterris sur une page me demandant confirmation de mon action, afin d'éviter les erreurs de manipulation.

Le MJ et moi pouvons modifier les PV de mon familier, pour les suivre pendant le combat.

Technique : 
Form classique, pas de HTMX pour la création/modification.
HTMX pour les PV.
